create table if not exists papers (
  id bigint generated by default as identity primary key,
  title text not null default '',
  authors text not null default '',
  venue text not null default '',
  year integer not null default 2026,
  field text not null default 'ai',
  status text not null default 'reading',
  citations integer not null default 0,
  progress integer not null default 0 check (progress >= 0 and progress <= 100),
  doi text not null default '',
  url text not null default '',
  tags text not null default '',
  abstract text not null default '',
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists queue (
  id bigint generated by default as identity primary key,
  title text not null default '',
  paper text not null default '',
  detail text not null default '',
  due text not null default '',
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists deadlines (
  id bigint generated by default as identity primary key,
  date text not null default '',
  title text not null default '',
  detail text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  title text not null default '',
  body text not null default '',
  date text not null default '',
  created_at timestamptz not null default now()
);

alter table papers enable row level security;
alter table queue enable row level security;
alter table deadlines enable row level security;
alter table activities enable row level security;

create policy "public read papers" on papers for select using (true);
create policy "public insert papers" on papers for insert with check (true);
create policy "public update papers" on papers for update using (true) with check (true);
create policy "public delete papers" on papers for delete using (true);

create policy "public read queue" on queue for select using (true);
create policy "public insert queue" on queue for insert with check (true);
create policy "public update queue" on queue for update using (true) with check (true);
create policy "public delete queue" on queue for delete using (true);

create policy "public read deadlines" on deadlines for select using (true);
create policy "public insert deadlines" on deadlines for insert with check (true);
create policy "public update deadlines" on deadlines for update using (true) with check (true);
create policy "public delete deadlines" on deadlines for delete using (true);

create policy "public read activities" on activities for select using (true);
create policy "public insert activities" on activities for insert with check (true);
create policy "public update activities" on activities for update using (true) with check (true);
create policy "public delete activities" on activities for delete using (true);
